name: Publish VSCode Extension

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup xvfb
        run: |
          sudo apt-get install xvfb
          export DISPLAY=:99.0
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: Package extension
        run: npm install -g vsce

      - name: Publish to Marketplace
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
